### ISSUE TITLE
[PiP] Performance issues after having opened a large amount of "PiPs"

### ISSUE THREAD

**Issue by filipejsfreitas** [iChun/IssueTracker-Mods#4]
First, I'm calling "PiP" to the little window from where you see the PoV of someone else.

After opening (and closing) a lot of PiPs, memory usage starts increasing and you get huge lag spikes when the garbage collector tries to clear the memory. The Debug screen (F3) doesn't really show that, but Windows Task Manager shows insane memory usage. Also, if I open a PiP then remove it, the memory usage doesn't go down to the same values it was before (not sure if that's relevant or not as Minecraft might be filling up the memory with other stuff, obviously).

Also, here's the environment in which this happened:
Windows 7 64 bits
Java (JDK) 64 bits
Minecraft 1.7.2, Forge 10.12.2.1147, Installed Mods are iChunUtils, PiP (obviously) and Optifine.

PS: Same happens without Optifine, but it's not as bad and it takes a bit longer for it to happen. Also, if this is in some way related to Optifine, I would like to get a fix because it improves the performance of the game a lot because I don't have the best computer in the world.

**Comment by iChun** [comment]
What version of PiP was this?

**Comment by filipejsfreitas** [comment]
PiP 3.0.3, iChunUtils 3.2.1, Optifine HD D1 (Not the ultra version)

**Comment by iChun** [comment]
I just checked, you must be adding a lot/removing a lot of PiPs in one session for the memory to start bogging you down. I had to add and consecutively remove >10 PiPs before I started to notice RAM impact. But I'll look into still.

**Comment by filipejsfreitas** [comment]
Yes, that's what I've been doing. I'm a server moderator, and I saw this mod and it represents accurately the player's PoV, and suits me perfectly when trying to see what players see. Helped already catch a lot of hackers, but I have to restart the game each 30 minutes otherwise my FPS drops like crazy and memory goes insane.

EDIT: Here I go catch one more :P
And another EDIT: Banned! :D I love these guys that instantly turn 180º when someone appears 1 block away from them...

**Comment by iChun** [comment]
I've been digging around for the source, I found it, but it's not easily fixed. I've managed to reduce most of the memory leaks, but not entirely. Each new PiP you create will give you a leak about 1mb. Hopefully this is more bearable for you compared to the previous 5mb leaks?

Also if you're curious. It's on OpenGL leak, which is why it wasn't showing up with MC's ingame debug.

**Comment by iChun** [comment]
Actually, the leak is a bit more than that.. but at least it goes down, right? :S

**Comment by filipejsfreitas** [comment]
Yeah, it's for sure a good improvement!

**Comment by iChun** [comment]
I've released the update, X.0.4 should patch the leaks a bit. It's the best I can do, so I'm gonna be closing this for now. I would advise against making so many PiPs, Maybe do something using PiP's selective view feature?

**Comment by filipejsfreitas** [comment]
I've been testing this for the last hour. Yes, this is for sure an improvement, haven't restarted MC yet and I still don't need to.

**Comment by iChun** [comment]
That's great. At least it confirms it's plugged for more than just me.

**Comment by filipejsfreitas** [comment]
Just a question... Did you make any kind of change that makes this only compatible with 1.7.10? I tried to run it in 1.7.2 and the game crashes because EntityClientPlayerMP can't be cast to EntityOtherPlayerMP.
Here's the head of the stacktrace: (before this is the FML event bus calling your methods)
java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.client.entity.EntityOtherPlayerMP
    at pip.common.core.PiPInfo.renderIntoFramebuffer(PiPInfo.java:70)
    at pip.common.core.TickHandlerClient.onRenderTick(TickHandlerClient.java:149)

(Yes yes, I know you don't like stack traces without pastebin, but I mean, just 3 lines, is that such a big deal? :\ )

I'm downgrading for now otherwise I can't go in 1.7.2, I hope you can fix this :\

Oh and yes, I do need a 1.7.2 version as some servers aren't yet updated to 1.7.5+.

**Comment by iChun** [comment]
I make ONE tiny change. Urgh geez

**Comment by filipejsfreitas** [comment]
I know that feeling too

**Comment by iChun** [comment]
Fixed. 1.6.4 version is unaffected. Redownload and reinstall should fix the crash issue. It should have crashed me in my testing but somehow did not, so I'm puzzled. Oh wells, thanks for the report.

**Comment by filipejsfreitas** [comment]
Yeah, downgrading didn't actually solve it. Now something is null pointing. Updating now.

**Comment by iChun** [comment]
And I wanna add on that you pulled me out of bed (I was about to sleep and was checking my emails in bed) to fix this. :P 

Also the mod doesn't work for 1.7.10 yet. Most of my mods aren't working for 1.7.10. I'll only start on 1.7.10 when I finish Sync for 1.7.2

**Comment by iChun** [comment]
The new file size should be 24,136 bytes if that matters.

**Comment by filipejsfreitas** [comment]
You could have gone to bed, it's not a big deal for today, it's 1:30am for me so... I should probably be in bed by now :P

**Comment by iChun** [comment]
It's a crash issue. Whenever it involves crashing I find it a big issue :/

**Comment by filipejsfreitas** [comment]
Btw, should I update iChunUtil to 3.3.0?

**Comment by iChun** [comment]
Yes. PiP requires it.

**Comment by filipejsfreitas** [comment]
Ok, thanks!

**Comment by iChun** [comment]
FML should have shat at you for not having the right dependency version of iChunUtil.

**Comment by filipejsfreitas** [comment]
When I downgraded I downgraded iChunUtil too, so I was just asking because I didn't remember if you said to update. Thanks anyway!

**Comment by filipejsfreitas** [comment]
If you were looking at my launcher you would see how many "Crash Report" tabs are open... They were all because of PiP! Let me just give it a test and see if it works now.

**Comment by filipejsfreitas** [comment]
It crashed with the same issue and yes, the file size is correct. Fix it tomorrow, I don't mind, everyone needs to sleep. Thanks still!

**Comment by iChun** [comment]
I'll just sit here in bed waiting for my phone to go off cause of another
email :X

**Comment by filipejsfreitas** [comment]
I am actually going to try to delete the config files, just in case. Wait a sec.

**Comment by filipejsfreitas** [comment]
http://pastebin.com/L6chW1SQ

I should note it only happens when I am actually in range of any player that I have a PiP for. If it's just rendering their head it works just fine. This is the same exception from when I downgraded, might be me?

And yes, in the stack trace, before that, it's the FML event bus calling the event handler.

**Comment by iChun** [comment]
Are you sneaking?

**Comment by filipejsfreitas** [comment]
Me? No, who I'm trying to see I'm not sure, I get a blue screen before I can actually see.
Let me identify that.

**Comment by filipejsfreitas** [comment]
Question... is the player head ment to disappear when I toggle PiP off with the key in the config? For me it just makes it a little bit darker.

**Comment by filipejsfreitas** [comment]
I was under water when I crashed.

**Comment by iChun** [comment]
I need your mods list. Those aren't vanilla calls.

**Comment by iChun** [comment]
Gimme your FML Log

**Comment by filipejsfreitas** [comment]
Yeah, I get it. I took out optifine and it works fine now. If you still want FML log I can go get it, just a sec.

**Comment by iChun** [comment]
Ah, Dang optifine, ew optifine.

**Comment by iChun** [comment]
It's fine. I generally don't support optifine anyways. They mess up things more than they fix sometimes. Now I can go to sleep \o/

**Comment by filipejsfreitas** [comment]
Yeah, Optifine was working fine before, I don't know why it's crashing now, but I can play without it. Thanks! I will also go sleep, 2am, good night/evening/whatever, not an english native speaker :P

**Comment by iChun** [comment]
What was your previous version of PiP?

**Comment by filipejsfreitas** [comment]
3.0.3

**Comment by iChun** [comment]
Shouldn't be any new issue. I'll see what I can do, moving this issue to a new issue.
